### PR TITLE
Add code examples to Email.rst

### PR DESCRIPTION
**Pull request by koritnik**
* add missing code examples

### CODE REVIEW

**Comment by sypets** [comment]
You cannot make changes to the ViewHelper reference here. The ViewHelper reference is automatically generated from the source code. The source code was already changed, but it was not regenerated. I will report this in the TYPO3 Slack channel `#typo3-documentation`.

Please see the file CONTRIBUTING.rst in this manual: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper/blob/master/CONTRIBUTING.rst

Contribution is generally very welcome and it's great that you want to contribute. You can contribute to most other TYPO3 manuals. (You will usually see an "Edit on GitHub" button on the top if this is possible), e.g. https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ExtensionArchitecture/Index.html

See also: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocsOfficial/Index.html

**Comment by sypets** [comment]
Opened issue: #31

**Comment by koritnik** [comment]
Ok. Wasnt aware of that. Sorry and Thanks.

**Comment by sypets** [comment]
@koritnik It was good, that you pointed it out. Just the wrong repo. 

I meant to take care of it but must setup local rendering for ViewHelper reference first. Hopefully, we will later add documentation for that and then contributing should be easier.

Apology for the confusion - I do find it a little confusing right now. Don't let that keep you from making further contributions!

**Pull request closed without merging**
