### PR TITLE
[TASK] Remove outdated comment

### PR DESCRIPTION
**Pull request by georgringer**
According to https://forge.typo3.org/issues/103142 this works

### CODE REVIEW

**Review by brotkrueml — COMMENTED** [review]
The view helper documentation is rendered automatically from the docblocks of the class. Please change it there, then it should be changed also here after merging:
https://github.com/TYPO3/typo3/blob/main/typo3/sysext/fluid/Classes/ViewHelpers/Format/CaseViewHelper.php#L44

**Comment by andreaskienast** [comment]
Patch is pending at https://review.typo3.org/c/Packages/TYPO3.CMS/+/83034.

**Comment by georgringer** [comment]
thanks!

**Comment by brotkrueml** [comment]
And already merged and rendered:
https://docs.typo3.org/other/typo3/view-helper-reference/12.4/en-us/typo3/fluid/latest/Format/Case.html

@georgringer Thanks for bringing this up.

**Pull request closed without merging**
